units = [
    ["c.", "C.", "Cup", "cup", "Cups", "cups"],
    ["T.", "Tbsp.", "tbsp.", "Tablespoon", "tablespoon", "Tablespoons", "tablespoons"],
    ["t.", "Tsp.", "tsp.", "Teaspoon", "teaspoon", "Teaspoons", "teaspoons"],
    ["lb.", "lbs.", "Pound", "pound", "Pounds", "pounds"],
    ["oz.", "ozs.", "Ounce", "ounce", "Ounces", "ounces"],
    ["pt.", "pts.", "Pint", "pint", "Pints", "pints"],
    ["qt.", "qts.", "Quart", "quart", "Quarts", "quarts"],
    ["gal.", "gals.", "Gallon", "gallon", "Gallons", "gallons"],
    ["ctn.", "ctns.", "Carton", "carton", "Cartons", "cartons"],
    ["g.", "gs.", "Gram", "gram", "Grams", "grams"],
    ["mg.", "mgs.", "Milligram", "milligram", "Milligrams", "milligrams"],
    ["l.", "ls.", "Liter", "liter", "Liters", "liters"],
    ["pkg.", "pkgs.", "Package", "package", "Packages", "packages"],
    ["pkt.", "pkts.", "Packet", "packet", "Packets", "packets"],
    ["pcs.", "Piece", "piece", "Pieces", "pieces"],
    ["env.", "envs.", "Envelope", "envelope", "Envelopes", "envelopes"],
    ["bg.", "bgs.", "Bag", "bag", "Bags", "bags"],
    ["bx.", "bxs.", "Box", "box", "Boxes", "boxes"],
    ["lf.", "lfs.", "Loaf", "loaf", "Loafs", "loafs"],
    ["cn.", "cns.", "Can", "can", "Cans", "cans"],
    ["clv.", "clvs.", "Clove", "clove", "Cloves", "cloves"],
    ["cb.", "cbs.", "Cube", "cube", "Cubes", "cubes"],
    ["st.", "sts.", "Stick", "stick", "Sticks", "sticks"],
    ["pn.", "pns.", "Pinch", "pinch", "Pinches", "pinches"],
    ["bn.", "bns.", "Bunch", "bunch", "Bunches", "bunches"],
    ["d.", "ds.", "Dash", "dash", "Dashes", "dashes"],
    ["btl.", "btls.", "Bottle", "bottle", "Bottles", "bottles"],
    ["hd.", "hds.", "Head", "head", "Heads", "heads"],
    ["slc.", "slcs.", "Slice", "slice", "Slices", "slices"],
    ["stlk.", "stlks.", "Stalk", "stalk", "Stalks", "stalks"],
    ["spg.", "spgs.", "Sprig", "sprig", "Sprigs", "sprigs"],
]
